# Netlify configuration file

# Build settings for your frontend
[build]
  command = "npm run build"
  publish = "dist"

# Serverless Functions settings
[functions]
  directory = "netlify/functions"
  # Use the esbuild bundler for modern JavaScript (ESM) support
  node_bundler = "esbuild"